export const ACTIONS = [
  {
    id: 'notes',
    icon: '📝',
    title: 'Smart Notes',
    desc: 'Format, organize & summarize your content',
    gradient: 'linear-gradient(135deg, #1a5fd4, #06b6d4)',
    color: '#1a6fe0',
    inputType: 'textarea',
    field: 'content',
    label: 'Your content',
    placeholder: 'Paste any text — notes, articles, reports...',
    isCombined: true,
    combineType: 'notes',
  },
  {
    id: 'meetings',
    icon: '🎯',
    title: 'Meeting Hub',
    desc: 'Minutes, analysis & action items',
    gradient: 'linear-gradient(135deg, #002fa7, #1a5fd4)',
    color: '#1a5fd4',
    inputType: 'textarea',
    field: 'transcript',
    label: 'Notes or transcript',
    placeholder: 'Paste meeting notes, full transcript, or import from Fireflies...',
    isCombined: true,
    combineType: 'meetings',
    fireflies: true,
  },
  {
    id: 'mail',
    icon: '✉️',
    title: 'Draft Mail',
    desc: 'Professional emails in seconds',
    gradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
    color: '#f59e0b',
    inputType: 'textarea',
    field: 'content',
    label: 'Email brief',
    placeholder: 'Describe the email: who, what, tone...',
  },
  {
    id: 'image',
    icon: '🔍',
    title: 'Image OCR',
    desc: 'Extract text from any image',
    gradient: 'linear-gradient(135deg, #14b8a6, #0d9488)',
    color: '#14b8a6',
    inputType: 'file',
    field: 'image',
    label: 'Upload image',
    placeholder: '',
  },
  {
    id: 'dictionary',
    icon: '📖',
    title: 'Dictionary',
    desc: 'AI-powered word intelligence',
    gradient: 'linear-gradient(135deg, #1a5fd4, #6366f1)',
    color: '#6366f1',
    inputType: 'text',
    field: 'word',
    label: 'Word or phrase',
    placeholder: 'Enter a word or phrase...',
  },
  {
    id: 'flowchart',
    icon: '🔀',
    title: 'Flowchart',
    desc: 'Generate Mermaid diagrams',
    gradient: 'linear-gradient(135deg, #f43f5e, #e11d48)',
    color: '#f43f5e',
    inputType: 'textarea',
    field: 'content',
    label: 'Process description',
    placeholder: 'Describe the process or workflow to visualize...',
  },
];
